
/*DDL 信息*/------------

CREATE TABLE `car_brand` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `firstletter` varchar(50) DEFAULT NULL,
  `linkurl` varchar(150) DEFAULT NULL,
  `carnum` mediumint(6) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=190 DEFAULT CHARSET=utf8



/*DDL 信息*/------------

CREATE TABLE `car_series` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `firm` varchar(50) NOT NULL,
  `firmurl` varchar(150) DEFAULT NULL,
  `levelname` varchar(50) DEFAULT NULL,
  `model` varchar(50) DEFAULT NULL,
  `modelurl` varchar(150) DEFAULT NULL,
  `brandurl` varchar(150) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1766 DEFAULT CHARSET=utf8


/*DDL 信息*/------------

CREATE TABLE `car_model_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type_name` varchar(50) NOT NULL COMMENT '车型',
  `jid` int(11) NOT NULL,
  `full_type_name` varchar(100) NOT NULL COMMENT '车型全称',
  `firm_price` char(10) DEFAULT '0.00万' COMMENT '厂商指导价',
  `firm` char(20) DEFAULT '' COMMENT '厂商',
  `grade` char(20) DEFAULT '' COMMENT '级别：微型车,小型车,紧凑型车,中型车,中大型车,豪华车,小型SUV,紧凑型SUV,中型SUV,中大型SUV,全尺寸SUV,MPV,跑车,皮卡,微面,轻客,微卡',
  `engine` varchar(40) DEFAULT '' COMMENT '发动机',
  `gear_box` varchar(40) DEFAULT '' COMMENT '变速箱',
  `cubage` varchar(40) DEFAULT '' COMMENT '长×宽×高(mm)',
  `detail_body_structure` varchar(40) DEFAULT '' COMMENT '车身结构',
  `max_speed` int(11) DEFAULT '0' COMMENT '最高车速(km/h)',
  `official_acceleration` decimal(6,2) DEFAULT '0.00' COMMENT '官方0-100km/h加速(s)',
  `measure_acceleration` decimal(6,2) DEFAULT '0.00' COMMENT '实测0-100km/h加速(s)',
  `measure_brake` decimal(6,2) DEFAULT '0.00' COMMENT '实测100-0km/h制动(m)',
  `measure_fuel_consumption` decimal(6,2) DEFAULT '0.00' COMMENT '实测油耗(L)',
  `combine_fuel_consumption` decimal(6,2) DEFAULT '0.00' COMMENT '工信部综合油耗(L)',
  `vehicle_warranty` varchar(40) DEFAULT '' COMMENT '整车质保',
  `car_length` int(11) DEFAULT '0' COMMENT '长度(mm)',
  `car_width` int(11) DEFAULT '0' COMMENT '宽度(mm)',
  `car_height` int(11) DEFAULT '0' COMMENT '高度(mm)',
  `wheelbase` int(11) DEFAULT '0' COMMENT '轴距(mm)',
  `front_track` int(11) DEFAULT '0' COMMENT '前轮距(mm)',
  `rear_track` int(11) DEFAULT '0' COMMENT '后轮距(mm)',
  `min_ground_clearance` int(11) DEFAULT '0' COMMENT '最小离地间隙(mm)',
  `curb_weight` int(11) DEFAULT '0' COMMENT '整备质量(Kg)',
  `body_structure` varchar(20) DEFAULT '' COMMENT '车身结构',
  `door_number` tinyint(4) DEFAULT '0' COMMENT '车门数(个)',
  `seat_number` tinyint(4) DEFAULT '0' COMMENT '座位数(个)',
  `tank_capacity` tinyint(4) DEFAULT '0' COMMENT '油箱容积(L)',
  `luggage_volume` tinyint(4) DEFAULT '0' COMMENT '行李厢容积(L)',
  `engine_model` varchar(40) DEFAULT '' COMMENT '发动机型号',
  `emission` int(11) DEFAULT '0' COMMENT '排量(mL)',
  `emission_liter` decimal(4,1) DEFAULT '0.0' COMMENT '排量(L)',
  `intake_form` varchar(40) DEFAULT '' COMMENT '进气形式',
  `cylinder_arrange` varchar(40) DEFAULT '' COMMENT '气缸排列形式',
  `cylinder_number` tinyint(4) DEFAULT '0' COMMENT '气缸数(个)',
  `cylinder_valve` tinyint(4) DEFAULT '0' COMMENT '每缸气门数(个)',
  `compression_ratio` decimal(6,2) DEFAULT '0.00' COMMENT '压缩比',
  `air_supply` varchar(40) DEFAULT '' COMMENT '配气机构',
  `bore` smallint(6) DEFAULT '0' COMMENT '缸径',
  `stroke` decimal(6,2) DEFAULT '0.00' COMMENT '行程',
  `max_horsepower` smallint(6) DEFAULT '0' COMMENT '最大马力(Ps)',
  `max_power` smallint(6) DEFAULT '0' COMMENT '最大功率(kW)',
  `max_power_speed` smallint(6) DEFAULT '0' COMMENT '最大功率转速(rpm)',
  `max_torque` smallint(6) DEFAULT '0' COMMENT '最大扭矩(N·m)',
  `max_torque_speed` smallint(6) DEFAULT '0' COMMENT '最大扭矩转速(rpm)',
  `engine_specific_technology` varchar(40) DEFAULT '' COMMENT '发动机特有技术',
  `fuel_form` varchar(40) DEFAULT '' COMMENT '燃料形式',
  `fuel_grade` varchar(40) DEFAULT '' COMMENT '燃油标号',
  `fuel_supply_means` varchar(40) DEFAULT '' COMMENT '供油方式',
  `cylinder_material` varchar(40) DEFAULT '' COMMENT '缸盖材料',
  `block_material` varchar(40) DEFAULT '' COMMENT '缸体材料',
  `environment_standards` varchar(40) DEFAULT '' COMMENT '环保标准',
  `max_motor_power` smallint(6) DEFAULT '0' COMMENT '电动机最大功率(kW)',
  `max_motor_torque` smallint(6) DEFAULT '0' COMMENT '电动机最大扭矩(N·m)',
  `battery_support_mileage` smallint(6) DEFAULT '0' COMMENT '电池支持最高续航里程(km)',
  `abbreviation` varchar(40) DEFAULT '' COMMENT '简称',
  `gear_number` tinyint(4) DEFAULT '0' COMMENT '挡位个数',
  `gearbox_type` varchar(40) DEFAULT '' COMMENT '变速箱类型',
  `drive_mode` varchar(40) DEFAULT '' COMMENT '驱动方式',
  `four_wheel_drive_form` varchar(40) DEFAULT '' COMMENT '四驱形式',
  `center_diff_structure` varchar(40) DEFAULT '' COMMENT '中央差速器结构',
  `front_suspension_type` varchar(40) DEFAULT '' COMMENT '前悬架类型',
  `rear_suspension_type` varchar(40) DEFAULT '' COMMENT '后悬架类型',
  `booster_type` varchar(40) DEFAULT '' COMMENT '助力类型',
  `chassis_body_structure` varchar(40) DEFAULT '' COMMENT '底盘转向车体结构',
  `front_brake_type` varchar(40) DEFAULT '' COMMENT '前制动器类型',
  `rear_brake_type` varchar(40) DEFAULT '' COMMENT '后制动器类型',
  `parking_brake_type` varchar(40) DEFAULT '' COMMENT '驻车制动类型',
  `front_tire_specification` varchar(40) DEFAULT '' COMMENT '前轮胎规格',
  `tear_tire_specification` varchar(40) DEFAULT '' COMMENT '后轮胎规格',
  `spare_tire_specification` varchar(40) DEFAULT '' COMMENT '备胎规格',
  `main_airbag` varchar(40) DEFAULT '' COMMENT '驾驶座安全气囊',
  `sub_airbag` varchar(40) DEFAULT '' COMMENT '副驾驶安全气囊',
  `main_sub_airbag` varchar(40) DEFAULT '' COMMENT '主/副驾驶座安全气囊',
  `front_side_airbag` varchar(40) DEFAULT '' COMMENT '前排侧气囊',
  `rear_side_airbag` varchar(40) DEFAULT '' COMMENT '后排侧气囊',
  `front_rear_side_airbag` varchar(40) DEFAULT '' COMMENT '前/后排侧气囊',
  `front_head_airbag` varchar(40) DEFAULT '' COMMENT '前排头部气囊(气帘)',
  `rear_head_airbag` varchar(40) DEFAULT '' COMMENT '后排头部气囊(气帘)',
  `front_rear_head_airbag` varchar(40) DEFAULT '' COMMENT '前/后排头部气囊(气帘)',
  `knee_airbag` varchar(40) DEFAULT '' COMMENT '膝部气囊',
  `tire_pressure_monitor_device` varchar(40) DEFAULT '' COMMENT '胎压监测装置',
  `zero_tire_pressure_trave` varchar(40) DEFAULT '' COMMENT '零胎压继续行驶',
  `seat_belt_prompt` varchar(40) DEFAULT '' COMMENT '安全带未系提示',
  `isofix_child_seat_interface` varchar(40) DEFAULT '' COMMENT 'ISOFIX儿童座椅接口',
  `latch_seat_interface` varchar(40) DEFAULT '' COMMENT 'LATCH座椅接口(兼容ISOFIX)',
  `child_seat_interface` varchar(40) DEFAULT '' COMMENT '儿童座椅接口',
  `electronic_anti_theft` varchar(40) DEFAULT '' COMMENT '发动机电子防盗',
  `car_central_lock` varchar(40) DEFAULT '' COMMENT '车内中控锁',
  `remote_key` varchar(40) DEFAULT '' COMMENT '遥控钥匙',
  `keyless_start_system` varchar(40) DEFAULT '' COMMENT '无钥匙启动系统',
  `keyless_entry_system` varchar(40) DEFAULT '' COMMENT '无钥匙进入系统',
  `abs_anti_lock` varchar(40) DEFAULT '' COMMENT 'ABS防抱死',
  `brake_force_distribution` varchar(40) DEFAULT '' COMMENT '制动力分配(EBD/CBC等)',
  `brake_assist` varchar(40) DEFAULT '' COMMENT '刹车辅助(EBA/BAS/BA等)',
  `traction_control` varchar(40) DEFAULT '' COMMENT '牵引力控制(ASR/TCS/TRC等)',
  `vehicle_stability_control` varchar(40) DEFAULT '' COMMENT '车身稳定控制(ESC/ESP/DSC等)',
  `automatic_parking` varchar(40) DEFAULT '' COMMENT '自动驻车/上坡辅助',
  `hill_descent` varchar(40) DEFAULT '' COMMENT '陡坡缓降',
  `variable_suspension` varchar(40) DEFAULT '' COMMENT '可变悬架',
  `air_suspension` varchar(40) DEFAULT '' COMMENT '空气悬架',
  `variable_steer_ratio` varchar(40) DEFAULT '' COMMENT '可变转向比',
  `front_axle_limited_slip` varchar(40) DEFAULT '' COMMENT '前桥限滑差速器/差速锁',
  `center_lock_function` varchar(40) DEFAULT '' COMMENT '中央差速器锁止功能',
  `tear_axle_limited_slip` varchar(40) DEFAULT '' COMMENT '后桥限滑差速器/差速锁',
  `electric_sunroof` varchar(40) DEFAULT '' COMMENT '电动天窗',
  `panoramic_sunroof` varchar(40) DEFAULT '' COMMENT '全景天窗',
  `sport_package` varchar(40) DEFAULT '' COMMENT '运动外观套件',
  `alloy_wheels` varchar(40) DEFAULT '' COMMENT '铝合金轮毂',
  `electric_door` varchar(40) DEFAULT '' COMMENT '电动吸合门',
  `leather_wheel` varchar(40) DEFAULT '' COMMENT '真皮方向盘',
  `steering_wheel_up_and_down` varchar(40) DEFAULT '' COMMENT '方向盘上下调节',
  `steering_wheel_before_and_after` varchar(40) DEFAULT '' COMMENT '方向盘前后调节',
  `steering_wheel_adjust` varchar(40) DEFAULT '' COMMENT '方向盘调节',
  `steering_wheel_electronic_adjust` varchar(40) DEFAULT '' COMMENT '方向盘电动调节',
  `multi_steering_wheel` varchar(40) DEFAULT '' COMMENT '多功能方向盘',
  `steering_wheel_shift` varchar(40) DEFAULT '' COMMENT '方向盘换挡',
  `steering_wheel_heat` varchar(40) DEFAULT '' COMMENT '方向盘加热',
  `cruise_control` varchar(40) DEFAULT '' COMMENT '定速巡航',
  `former_radar` varchar(40) DEFAULT '' COMMENT '前驻车雷达',
  `after_reversing_radar` varchar(40) DEFAULT '' COMMENT '后驻车雷达',
  `former_after_radar` varchar(40) DEFAULT '' COMMENT '前/后驻车雷达',
  `reversing_video` varchar(40) DEFAULT '' COMMENT '倒车视频影像',
  `trip_computer_display` varchar(40) DEFAULT '' COMMENT '行车电脑显示屏',
  `head_up_digital_display` varchar(40) DEFAULT '' COMMENT 'HUD抬头数字显示',
  `leather_seat` varchar(40) DEFAULT '' COMMENT '真皮/仿皮座椅',
  `sports_style_seat` varchar(40) DEFAULT '' COMMENT '运动风格座椅',
  `seat_height_adjust` varchar(40) DEFAULT '' COMMENT '座椅高低调节',
  `lumbar_support_adjust` varchar(40) DEFAULT '' COMMENT '腰部支撑调节',
  `shoulder_support_adjust` varchar(40) DEFAULT '' COMMENT '肩部支撑调节',
  `driving_position_electric_adjust` varchar(40) DEFAULT '' COMMENT '驾驶位电动调节',
  `copilot_electric_adjust` varchar(40) DEFAULT '' COMMENT '副驾驶位电动调节',
  `main_sub_electric_adjust` varchar(40) DEFAULT '' COMMENT '主/副驾驶座电动调节',
  `second_row_angle_adjust` varchar(40) DEFAULT '' COMMENT '第二排靠背角度调节',
  `second_row_seat_move` varchar(40) DEFAULT '' COMMENT '第二排座椅移动',
  `rear_seat_electric_adjust` varchar(40) DEFAULT '' COMMENT '后排座椅电动调节',
  `electric_seat_memory` varchar(40) DEFAULT '' COMMENT '电动座椅记忆',
  `front_seat_heat` varchar(40) DEFAULT '' COMMENT '前排座椅加热',
  `rear_seat_heat` varchar(40) DEFAULT '' COMMENT '后排座椅加热',
  `front_rear_seat_heat` varchar(40) DEFAULT '' COMMENT '前/后排座椅加热',
  `front_seat_ventilation` varchar(40) DEFAULT '' COMMENT '前排座椅通风',
  `rear_seat_ventilation` varchar(40) DEFAULT '' COMMENT '后排座椅通风',
  `front_rear_seat_ventilation` varchar(40) DEFAULT '' COMMENT '前/后排座椅通风',
  `front_seat_massage` varchar(40) DEFAULT '' COMMENT '前排座椅按摩',
  `rear_seat_massage` varchar(40) DEFAULT '' COMMENT '后排座椅按摩',
  `front_rear_seat_massage` varchar(40) DEFAULT '' COMMENT '前/后排座椅按摩',
  `rear_seat_overall_recline` varchar(40) DEFAULT '' COMMENT '后排座椅整体放倒',
  `rear_seat_proportion_recline` varchar(40) DEFAULT '' COMMENT '后排座椅比例放倒',
  `rear_seat_recline` varchar(40) DEFAULT '' COMMENT '后排座椅放倒方式',
  `third_row_seat` varchar(40) DEFAULT '' COMMENT '第三排座椅',
  `front_seat_center_armrest` varchar(40) DEFAULT '' COMMENT '前座中央扶手',
  `rear_seat_center_armrest` varchar(40) DEFAULT '' COMMENT '后座中央扶手',
  `front_rear_seat_center_armrest` varchar(40) DEFAULT '' COMMENT '前/后中央扶手',
  `rear_cup_holders` varchar(40) DEFAULT '' COMMENT '后排杯架',
  `electric_trunk` varchar(40) DEFAULT '' COMMENT '电动后备厢',
  `gps_navigation_system` varchar(40) DEFAULT '' COMMENT 'GPS导航系统',
  `position_interactive_service` varchar(40) DEFAULT '' COMMENT '定位互动服务',
  `center_console_screen` varchar(40) DEFAULT '' COMMENT '中控台彩色大屏',
  `human_computer_interaction_system` varchar(40) DEFAULT '' COMMENT '人机交互系统',
  `built_in_hard_drive` varchar(40) DEFAULT '' COMMENT '内置硬盘',
  `bluetooth` varchar(40) DEFAULT '' COMMENT '蓝牙/车载电话',
  `car_tv` varchar(40) DEFAULT '' COMMENT '车载电视',
  `rear_lcd_screen` varchar(40) DEFAULT '' COMMENT '后排液晶屏',
  `external_audio_interface` varchar(40) DEFAULT '' COMMENT '外接音源接口(AUX/USB/iPod等)',
  `support_mp3` varchar(40) DEFAULT '' COMMENT 'CD支持MP3/WMA',
  `single_disc_cd` varchar(40) DEFAULT '' COMMENT '单碟CD',
  `virtual_multi_disc_cd` varchar(40) DEFAULT '' COMMENT '虚拟多碟CD',
  `multi_disc_cd_system` varchar(40) DEFAULT '' COMMENT '多碟CD系统',
  `cd_system` varchar(40) DEFAULT '' COMMENT 'CD系统',
  `single_disc_dvd` varchar(40) DEFAULT '' COMMENT '单碟DVD',
  `multi_disc_dvd_system` varchar(40) DEFAULT '' COMMENT '多碟DVD系统',
  `dvd_system` varchar(40) DEFAULT '' COMMENT 'DVD系统',
  `mutlti_system` varchar(40) DEFAULT '' COMMENT '多媒体系统',
  `horn_speaker_system1` varchar(40) DEFAULT '' COMMENT '2-3喇叭扬声器系统',
  `horn_speaker_system2` varchar(40) DEFAULT '' COMMENT '4-5喇叭扬声器系统',
  `horn_speaker_system3` varchar(40) DEFAULT '' COMMENT '6-7喇叭扬声器系统',
  `horn_speaker_system4` varchar(40) DEFAULT '' COMMENT '≥8喇叭扬声器系统',
  `horn_speaker_num` varchar(40) DEFAULT '' COMMENT '扬声器数量',
  `xenon_headlight` varchar(40) DEFAULT '' COMMENT '氙气大灯',
  `led_headlamp` varchar(40) DEFAULT '' COMMENT 'LED大灯',
  `daytime_running_light` varchar(40) DEFAULT '' COMMENT '日间行车灯',
  `automatic_headlight` varchar(40) DEFAULT '' COMMENT '自动头灯',
  `steering_headlight` varchar(40) DEFAULT '' COMMENT '转向头灯(辅助灯)',
  `front_fog_lamp` varchar(40) DEFAULT '' COMMENT '前雾灯',
  `height_adjust_headlight` varchar(40) DEFAULT '' COMMENT '大灯高度可调',
  `headlight_clean_system` varchar(40) DEFAULT '' COMMENT '大灯清洗装置',
  `ambient_light` varchar(40) DEFAULT '' COMMENT '车内氛围灯',
  `front_electric_windows` varchar(40) DEFAULT '' COMMENT '前电动车窗',
  `rear_power_windows` varchar(40) DEFAULT '' COMMENT '后电动车窗',
  `front_rear_power_windows` varchar(40) DEFAULT '' COMMENT '前/后电动车窗',
  `window_fangga_hand` varchar(40) DEFAULT '' COMMENT '车窗防夹手功能',
  `insulated_glass` varchar(40) DEFAULT '' COMMENT '防紫外线/隔热玻璃',
  `rear_mirror_adjust` varchar(40) DEFAULT '' COMMENT '后视镜电动调节',
  `rear_mirror_heat` varchar(40) DEFAULT '' COMMENT '后视镜加热',
  `inside_rear_mirror_auto_dimming` varchar(40) DEFAULT '' COMMENT '内后视镜自动防眩目',
  `outside_rear_mirror_auto_dimming` varchar(40) DEFAULT '' COMMENT '外后视镜自动防眩目',
  `inside_outside_rear_mirror_auto_dimming` varchar(40) DEFAULT '' COMMENT '内/外后视镜自动防眩目',
  `rear_mirror_power_fold` varchar(40) DEFAULT '' COMMENT '后视镜电动折叠',
  `rear_mirror_memory` varchar(40) DEFAULT '' COMMENT '后视镜记忆',
  `rear_window_sunshade` varchar(40) DEFAULT '' COMMENT '后风挡遮阳帘',
  `rear_side_sunshade` varchar(40) DEFAULT '' COMMENT '后排侧遮阳帘',
  `rear_side_privacy_glass` varchar(40) DEFAULT '' COMMENT '后排侧隐私玻璃',
  `make_up_mirror` varchar(40) DEFAULT '' COMMENT '遮阳板化妆镜',
  `rear_wiper` varchar(40) DEFAULT '' COMMENT '后雨刷',
  `sensing_wiper` varchar(40) DEFAULT '' COMMENT '感应雨刷',
  `manual_air_condition` varchar(40) DEFAULT '' COMMENT '手动空调',
  `automatic_air_condition` varchar(40) DEFAULT '' COMMENT '自动空调',
  `air_condition` varchar(40) DEFAULT '' COMMENT '空调控制方式',
  `rear_independent_air_condition` varchar(40) DEFAULT '' COMMENT '后排独立空调',
  `back_seat_outlet` varchar(40) DEFAULT '' COMMENT '后座出风口',
  `temperature_zone_control` varchar(40) DEFAULT '' COMMENT '温度分区控制',
  `car_air_condition` varchar(40) DEFAULT '' COMMENT '车内空气调节/花粉过滤',
  `car_refrigerator` varchar(40) DEFAULT '' COMMENT '车载冰箱',
  `automatic_parking_into_place` varchar(40) DEFAULT '' COMMENT '自动泊车入位',
  `engine_start_stop_technology` varchar(40) DEFAULT '' COMMENT '发动机启停技术',
  `and_line_auxiliary` varchar(40) DEFAULT '' COMMENT '并线辅助',
  `lane_departure_warning_system` varchar(40) DEFAULT '' COMMENT '车道偏离预警系统',
  `active_brake` varchar(40) DEFAULT '' COMMENT '主动刹车/主动安全系统',
  `entegral_active_steer` varchar(40) DEFAULT '' COMMENT '整体主动转向系统',
  `night_vision_systems` varchar(40) DEFAULT '' COMMENT '夜视系统',
  `split_screen_display` varchar(40) DEFAULT '' COMMENT '中控液晶屏分屏显示',
  `adaptive_cruise` varchar(40) DEFAULT '' COMMENT '自适应巡航',
  `panoramic_camera` varchar(40) DEFAULT '' COMMENT '全景摄像头',
  `body_color` varchar(100) DEFAULT '' COMMENT '车身颜色',
  `sort` smallint(5) NOT NULL DEFAULT '100' COMMENT '排序 按着降序排列',
  `is_onsale` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否在售：0-否,1-是',
  `create_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8226 DEFAULT CHARSET=utf8 COMMENT='具体车款'
